spring:
  application:
    name: discovery-service
server:
  port: 8761

eureka:
  server:
    wait-time-in-ms-when-sync-empty: 1000
  instance:
    hostname: localhost
    appname: eureka-discovery-service
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/


